# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Aphorism.create!(
  [
    {text: '人は心が愉快であれば終日歩んでも嫌になることはないが、心に憂いがあればわずか一里でも嫌になる。人生の行路もこれと同様で、人は常に明るく愉快な心をもって人生の行路を歩まねばならぬ。',
      name: 'ウィリアム・シェイクスピア'},
    {text: '私たち一人ひとりが航海しているこの人生の広漠とした大洋の中で、理性は羅針盤、情熱は疾風。',
      name: 'アレキサンダー・ポープ'},
    {text: '自分自身を信じてみるだけでいい。きっと、生きる道が見えてくる。',
      name: 'ヨハン・ヴォルフガング・フォン・ゲーテ'},
    {text: '人生という試合で最も重要なのは、休憩時間の得点である。',
      name: 'ナポレオン・ボナパルト'},
    {text: '一羽のツバメが来ても夏にはならないし、一日で夏になることもない。このように、一日もしくは短い時間で人は幸福にも幸運にもなりはしない。',
      name: 'アリストテレス'},
    {text: '人生とは自転車のようなものだ。倒れないようにするには走らなければならない。',
      name: 'アルベルト・アインシュタイン'},
    {text: '明日死ぬかのように生きよ。永遠に生きるかのように学べ。',
      name: 'マハトマ・ガンディー'},
    {text: '人間には不幸か、貧乏か、病気が必要だ。でないと人間はすぐに思いあがる。',
      name: 'イワン・セルゲーエヴィチ・ツルゲーネフ'},
    {text: '人生は道路のようなものだ。一番の近道は、たいてい一番悪い道だ。',
      name: 'フランシス・ベーコン'},
    {text: '絶えずあなたを何者かに変えようとする世界の中で、自分らしくあり続けること。それがもっとも素晴らしい偉業である。',
      name: 'ラルフ・ウォルドー・エマーソン'},
    {text: '自由とは責任を意味する。だから、たいていの人間は自由を恐れる。',
      name: 'ジョージ・バーナード・ショー'},
    {text: 'あちこち旅をしてまわっても、自分から逃げることはできない。',
      name: 'アーネスト・ミラー・ヘミングウェイ'},
    {text: 'すべてを今すぐに知ろうとは無理なこと。雪が解ければ見えてくる。',
      name: 'ヨハン・ヴォルフガング・フォン・ゲーテ'},
    {text: '成功は誕生日みたいなもの。待ちに待った誕生日がきても、自分はなにも変わらないでしょ。',
      name: 'オードリー・ヘプバーン'},
    {text: '世の中で成功を収めるには、馬鹿のように見せかけ、利口に行動することである。',
      name: 'ルイ・ド・モンテスキュー'},
    {text: '生きるとは呼吸することではない。行動することだ。',
      name: 'ジャン・ジャック・ルソー'},
    {text: 'どうにも乗り越えられない障害にぶつかった時は、頑固さほど役に立たないものはない。',
      name: 'シモーヌ・ド・ボーヴォワール'},
    {text: '常識とは十八歳までに身につけた偏見のコレクションのことをいう。',
      name: 'アルベルト・アインシュタイン'},
    {text: '一番大切なことは、単に生きることではなく、善く生きることである。',
      name: 'ソクラテス'},
    {text: '逃げた者はもう一度戦える。',
      name: 'デモステネス'},
    {text: '人生に失敗した人の多くは、諦めたときに自分がどれほど成功に近づいていたか気づかなかった人たちだ。',
      name: 'トーマス・エジソン'},
    {text: '人生は学校である。そこでは幸福より不幸の方が良い教師である。',
      name: 'ウラディミール・フリーチェ'},
    {text: '蝶はモグラではない。でも、そのことを残念がる蝶はいないだろう。',
      name: 'アルベルト・アインシュタイン'},
    {text: '人は、運命を避けようとしてとった道で、しばしば運命にであう。',
      name: 'ジャン・ド・ラ・フォンテーヌ'},
    {text: '自分の力に合うことだけしろ、その他の事は、おのずと道が開けてくるまで待て。。',
      name: '武者小路実篤'},
    {text: '自分になにができるかを知るより、なにができないかを知ることのほうが重要よ。',
      name: 'ルシル・デジレ・ボール'},
    {text: '事を成し遂げる者は愚直でなければならぬ。才走ってはうまくいかない。',
      name: '勝海舟'},
    {text: '慢心は人間の最大の敵だ。',
      name: 'ウィリアム・シェイクスピア'},
    {text: '森の分かれ道では人の通らぬ道を選ぼう。すべてが変わる。',
      name: 'ロバート・リー・フロスト'},
    {text: '扉に変わるかも知れないという、勝手な希望にとらわれて、壁をたたき続けてはいけないわ。',
      name: 'ココ・シャネル'},
    {text: '人生はクローズアップで見れば悲劇だが、ロングショットで見れば喜劇だ。',
      name: 'チャールズ・スペンサー・チャップリン'}
  ]
)

Animal.create!(
  [
    {animal_name: 'ブタ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/buta.jpg"), filename: 'buta.jpg')},
    {animal_name: 'ダチョウ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/dacho.jpg"), filename: 'dacho.jpg')},
    {animal_name: 'ハムスター',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/hamu.jpg"), filename: 'hamu.jpg')},
    {animal_name: 'ハリネズミ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/hari.jpg"), filename: 'hari.jpg')},
    {animal_name: 'ヒヨコ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/hiyoko.jpg"), filename: 'hiyoko.jpg')},
    {animal_name: 'イヌ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/inu.jpg"), filename: 'inu.jpg')},
    {animal_name: 'イヌ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/inu2.jpg"), filename: 'inu2.jpg')},
    {animal_name: 'カバ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/kaba.jpg"), filename: 'kaba.jpg')},
    {animal_name: 'カピバラ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/kapibara.jpg"), filename: 'kapibara.jpg')},
    {animal_name: 'キツネ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/kitsune.jpg"), filename: 'kitsune.jpg')},
    {animal_name: 'コアラ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/koara.jpg"), filename: 'koara.jpg')},
    {animal_name: 'クマ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/kuma.jpg"), filename: 'kuma.jpg')},
    {animal_name: 'ネコ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/neko.jpg"), filename: 'neko.jpg')},
    {animal_name: 'オウム',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/oumu.jpg"), filename: 'oumu.jpg')},
    {animal_name: 'パンダ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/panda.jpg"), filename: 'panda.jpg')},
    {animal_name: 'ペンギン',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/pengin.jpg"), filename: 'pengin.jpg')},
    {animal_name: 'ライオン',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/raion.jpg"), filename: 'raion.jpg')},
    {animal_name: 'ラッコ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/rakko.jpg"), filename: 'rakko.jpg')},
    {animal_name: 'レッサーパンダ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/ressapanda.jpg"), filename: 'ressapanda.jpg')},
    {animal_name: 'リス',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/risu.jpg"), filename: 'risu.jpg')},
    {animal_name: 'サイ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sai.jpg"), filename: 'sai.jpg')},
    {animal_name: 'サル',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/saru.jpg"), filename: 'saru.jpg')},
    {animal_name: 'シカ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/shika.jpg"), filename: 'shika.jpg')},
    {animal_name: 'シマウマ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/shimauma.jpg"), filename: 'shimauma.jpg')},
    {animal_name: 'シロクマ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/shirokuma.jpg"), filename: 'shirokuma.jpg')},
    {animal_name: 'タカ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/taka.jpg"), filename: 'taka.jpg')},
    {animal_name: 'タヌキ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/tanuki.jpg"), filename: 'tanuki.jpg')},
    {animal_name: 'トラ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/tora.jpg"), filename: 'tora.jpg')},
    {animal_name: 'ウサギ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/usagi.jpg"), filename: 'usagi.jpg')},
    {animal_name: 'ゾウ',animal_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/zou.jpg"), filename: 'zou.jpg')}
  ]
)

Snack.create!(
  [
    {snack_name: 'あめ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/candy.jpg"), filename: 'candy.jpg')},
    {snack_name: 'グミ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/gumi.jpg"), filename: 'gumi.jpg')},
    {snack_name: 'あめちゃん',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/candy2.jpg"), filename: 'candy2.jpg')},
    {snack_name: 'チョコレート',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/choco.jpg"), filename: 'choco.jpg')},
    {snack_name: 'チョコケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/choco-cake.jpg"), filename: 'choco-cake.jpg')},
    {snack_name: 'アイスクリーム',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/ice-cream.jpg"), filename: 'ice-cream.jpg')},
    {snack_name: 'プリン',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/purin.jpg"), filename: 'purin.jpg')},
    {snack_name: 'ヨーグルトケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/yogurt.jpg"), filename: 'yogurt.jpg')},
    {snack_name: '桜餅',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/sakura-mochi.jpg"), filename: 'sakura-moch.jpg')},
    {snack_name: 'マカロン',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/macaroon.jpg"), filename: 'macaroon.jpg')},
    {snack_name: 'カップケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/cap-cake.jpg"), filename: 'cap-cake.jpg')},
    {snack_name: 'シュークリーム',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/cream-puff.jpg"), filename: 'cream-puff.jpg')},
    {snack_name: 'ぜんざい',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/zenzai.jpg"), filename: 'zenzai.jpg')},
    {snack_name: 'たこ焼き',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/takoyaki.jpg"), filename: 'takoyaki.jpg')},
    {snack_name: 'うどん',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/udon.jpg"), filename: 'udon.jpg')},
    {snack_name: 'クッキー',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/cookie.jpg"), filename: 'cookie.jpg')},
    {snack_name: 'ケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/cake.jpg"), filename: 'cake.jpg')},
    {snack_name: 'クレープ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/crepe.jpg"), filename: 'crepe.jpg')},
    {snack_name: 'ロールケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/roll-cake.jpg"), filename: 'roll-cake.jpg')},
    {snack_name: 'パンケーキ',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/pancake.jpg"), filename: 'pancake.jpg')},
    {snack_name: '無し',snack_image: ActiveStorage::Blob.create_and_upload!(io: File.open("#{Rails.root}/db/fixtures/no-snack.jpg"), filename: 'no-snack.jpg')}
  ]
)